fix(export): fix ALB export when using newt
Merge in SPKR/keel-nflx from fix-alb-export to main

Squashed commit of the following:

commit ba27e69ec356f315b6c3e0b82c84ba0167ee4845
Author: Lorin Hochstein <lhochstein@netflix.com>
Date:   Wed May 4 15:23:13 2022 -0700

    fix(export): fix ALB export using newt

    Context

    Jeyrs is working on replicating load balancer resources into us-east-2,
    and is exploring whether he could use MD to export LB resources, and
    then publish a delivery config that would create the LBs in us-east-2.

    Problem

    I was showing him how he could use newt+MD to export existing load balancer resources, and when I tried to export the ALB from the spindemo app, saw this error:

    ```
    $ newt --app-type=spinnaker export --spinnaker-app=spindemo --service-account=spinnaker-team@netflix.com
    ...
    NOTICE  Exporting application-load-balancer spindemo-alb [aws/test]
    ...
    ERROR: Failed to export resource application-load-balancer spindemo-alb [aws/test]: api request: Unexpected response from https://spinnaker-api.mgmt.netflix.net:7004/managed/resources/export/aws/test/application-load-balancer/spindemo-alb?serviceAccount=spinnaker-team@netflix.com, expected 200 or 201 but got 500
    ```

    Keel can handle export of ALBs if the type specified is
    "applicationloadbalancer" or "applicationloadbalancers", but newt is
    passing the specified type in the URL path as
    "application-load-balancer"

    Solution

    Add `application-load-balancer` as a valid type for exporting ALBs.

    I tested this on my local machine and it worked.

(cherry picked from commit daa9f9c98d243662e719cc82f7d42f3648e523c7)